config/routes.rb
Rails.application.routes.draw do
  resources :competitors
  resources :calculation_categories
  #resources :customer_categories
  resources :inventory_categories
  #resources :inventories
  resources :units
  resources :accountant_preferences
  #resources :equipment
  resources :positions
  get 'static_pages/home'
  get 'static_pages/help'

  resources :customer_categories do
    collection do
      delete "restore/:id" => "customer_categories#restore", as: :restore
    end
  end
  resources :calculations do
    collection do
      get 'get_unit_and_price', to: "calculations#get_unit_and_price"
      get 'get_customers_prices', to: "calculations#get_customers_prices"
      get 'load_category_percents', to: "calculations#load_category_percents"
      delete "restore/:id" => "calculations#restore", as: :restore
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home' #'calculations#index'

  resources :equipment do
    resources :equipment_parameters do
      member do
        delete 'remove_item', to: 'equipment#remove_item'
      end
    end
  end

  resources :inventories do
    resources :inventory_parameters do
      member do
        delete 'remove_item', to: 'inventories#remove_item'
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.slim
h1 StaticPages#help
p Find me in app/views/static_pages/help.html.slim

app/views/static_pages/home.html.slim
h3.text-center.mt-5 Меню

.row.mb-5.mt-5.text-center
  .col-sm-4.col-xs-12.text-center
    = link_to 'НАСТРОЙКИ ФИНАНСОВЫЕ', accountant_preferences_path, class: 'btn btn-primary btn-lg'
  .col-sm-4.col-xs-12.text-center
    = link_to 'ДОЛЖНОСТИ', positions_path, class: 'btn btn-primary btn-lg'
  .col-sm-4.col-xs-12.text-center
    = link_to 'ОБОРУДОВАНИЕ', equipment_index_path, class: 'btn btn-primary btn-lg'

.row.mb-5.mt-5.text-center
  .col-sm-4.col-xs-12.text-center
    = link_to 'ЕДИНИЦЫ ИЗМЕРЕНИЯ', units_path, class: 'btn btn-primary btn-lg'
  /.col-sm-4.col-xs-12.text-center
    = link_to 'КАТЕГОРИИ ТМЦ', inventory_categories_path, class: 'btn btn-primary btn-lg'
  .col-sm-4.col-xs-12.text-center
    = link_to 'ТМЦ', inventory_categories_path, class: 'btn btn-primary btn-lg'
  /.col-sm-4.col-xs-12.text-center
    = link_to 'ОБОРУДОВАНИЕ', equipment_index_path, class: 'btn btn-primary btn-lg'

.row.mb-5.mt-5.text-center
  .col-sm-4.col-xs-12.text-center
    = link_to 'КАТЕГОРИИ ПОТРЕБИТЕЛЕЙ', customer_categories_path, class: 'btn btn-primary btn-lg'
  .col-sm-4.col-xs-12.text-center
    = link_to 'КАЛЬКУЛЯЦИИ', calculation_categories_path, class: 'btn btn-primary btn-lg'
  .col-sm-4.col-xs-12.text-center
    = link_to 'КОНКУРЕНТЫ', competitors_path, class: 'btn btn-primary btn-lg'