config/routes.rb
Rails.application.routes.draw do
  resources :competitors
  resources :calculation_categories
  #resources :customer_categories
  resources :inventory_categories
  #resources :inventories
  resources :units
  resources :accountant_preferences
  #resources :equipment
  resources :positions
  get 'static_pages/home'
  get 'static_pages/help'

  resources :customer_categories do
    collection do
      delete "restore/:id" => "customer_categories#restore", as: :restore
    end
  end
  resources :calculations do
    collection do
      get 'get_unit_and_price', to: "calculations#get_unit_and_price"
      get 'get_customers_prices', to: "calculations#get_customers_prices"
      get 'load_category_percents', to: "calculations#load_category_percents"
      delete "restore/:id" => "calculations#restore", as: :restore
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home' #'calculations#index'

  resources :equipment do
    resources :equipment_parameters do
      member do
        delete 'remove_item', to: 'equipment#remove_item'
      end
    end
  end

  resources :inventories do
    resources :inventory_parameters do
      member do
        delete 'remove_item', to: 'inventories#remove_item'
      end
    end
  end
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  has_many :inventory_parameters
  accepts_nested_attributes_for :inventory_parameters

  belongs_to :unit

  has_many :inventory_categories_inventories, :dependent => :destroy
  has_many :inventory_categories, through: :inventory_categories_inventories

  validates :name, presence: true

  def set_actual_parameter
    parameters = self.inventory_parameters
    return unless parameters.present?
    
    actual_parameter = parameters.where(actual: true)
    return if actual_parameter.present?

    parameters.set_actual
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy, :remove_item]

  def index
    @inventories = Inventory.where(deleted: false).order(name: :asc)
  end

  def show; end

  def new
    @inventory = Inventory.new
    @inventory.inventory_parameters.build
    @units = Unit.where(deleted: false).order(name: :asc).map { |u| [ u.name, u.id ] }
    @inventory_categories = collection_for_parent_select
  end

  def edit
    @inventory = Inventory.find(params[:id])
    @inventory_parameters = InventoryParameter.get_last(@inventory.id, 5)
    @units = Unit.order(name: :asc).map { |u| [ u.name, u.id ] }
    @inventory_categories = collection_for_parent_select
  end

  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        InventoryParameter.set_irrelevant(@inventory.id)
        @inventory.inventory_parameters.set_relevant
        flash[:success] = 'ТМЦ успешно создана.'
        format.html { redirect_to edit_inventory_path(@inventory) }
      else
        flash[:danger] = 'Ошибка создания ТМЦ.'
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        InventoryParameter.set_irrelevant(@inventory.id)
        @inventory.inventory_parameters.set_relevant
        flash[:success] = 'ТМЦ успешно отредактирована.'
        format.html { redirect_to edit_inventory_path(@inventory) }
      else
        flash[:danger] = 'Ошибка редактирования ТМЦ.'
        format.html { redirect_to edit_inventory_path(@inventory) }
      end
    end
  end

  def destroy
    @inventory.update_column(:deleted, true)
    respond_to do |format|
      InventoryParameter.set_irrelevant(@inventory.id)
      flash[:success] = 'ТМЦ успешно удалена.'
      format.html { redirect_to inventory_index_path }
    end
  end

  def remove_item
    item = InventoryParameter.find(params[:id])

    respond_to do |format|
      if item.destroy
        @inventory.set_actual_parameter
        flash[:success] = 'История успешно удалена.'
      else
        flash[:error] = 'Ошибка удаления истории.'
      end
      format.html { redirect_to edit_inventory_path(@inventory) }
    end
  end

  private

    def set_inventory
      id = params[:inventory_id].present? ? params[:inventory_id] : params[:id]
      @inventory = Inventory.find(id)
    end

    def inventory_params
      params.require(:inventory).permit(:name, :unit_id, :inventory_category_ids, inventory_parameters_attributes: [:id, :inventory_id, :price, :margin, :actual])
    end

    def collection_for_parent_select
      @categories = ancestry_options(InventoryCategory.unscoped.arrange(order: 'name')) {|i| "#{'-' * i.depth} #{i.name}" }
    end

    def ancestry_options(items)
    result = []
    items.map do |item, sub_items|
        result << [(("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" * item.depth) + item.name).html_safe, item.id]
        result += ancestry_options(sub_items) unless sub_items.blank?
    end
    result
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.slim
  = render 'layouts/errors', object: @inventory
  
  = form_for @inventory do |f|
    .row.mt-5
      .form-group.col-sm-6
        = f.label :inventory_category_ids, 'Категория', class: 'control-label small-label-placeholder'
        = f.select :inventory_category_ids, @inventory_categories, { include_blank: '...' }, class: 'form-control form-control-sm', required: true
    .row.mt-5
      .form-group.col-sm-6
        = f.text_field :name, class: 'form-control form-control-sm', required: true
        = f.label :name, 'Наименование', class: 'form-control-placeholder'
      .form-group.col-sm-2
        = f.label :unit_id, 'Ед. измерения', class: 'small-label-placeholder'
        = f.select :unit_id, @units, { include_blank: '' }, { class: 'form-control form-control-sm', required: true }
      = f.fields_for :inventory_parameters, @inventory.inventory_parameters.build do |ip|
        .form-group.col-sm-2
          = ip.text_field :price, class: 'form-control form-control-sm', required: true
          = ip.label :price, 'Стоимость, руб', class: 'form-control-placeholder'
        .form-group.col-sm-2
          = ip.text_field :margin, class: 'form-control form-control-sm', required: true
          = ip.label :margin, 'Наценка, %', class: 'form-control-placeholder'
    - if @inventory.persisted?
      hr
      .row.col-sm-12.col-xs-12.mb-2.text-muted.small
        .col-sm-2.col-xs-2
          | Стоимость, руб
        .col-sm-2.col-xs-2
          | Наценка, %
        .col-sm-2.col-xs-2
          | Дата
        .col-sm-2.col-xs-2
          | Создана
      hr.mb-1.mt-1
      - @inventory_parameters.each do |ip|
        .row.col-sm-12.col-xs-12.item-hystory-row
          .col-sm-2.col-xs-2
            = ip.price
          .col-sm-2.col-xs-2
            = ip.margin
          .col-sm-2.col-xs-2
            = ip.created_at.strftime('%d-%m-%Y / %H:%M')
            |&nbsp;
            - if ip.actual
              span.badge.bg-success.text-white
                | &nbsp;&nbsp;
            - else
              span.badge.bg-warning.text-white
                | &nbsp;&nbsp;
          .col-sm-2.col-xs-2
            | Имя пользователя
            |&nbsp;
            = link_to remove_item_inventory_inventory_parameter_path(@inventory, ip), data: { confirm: 'Вы уверены?' }, method: :delete do
              == material_icon.delete_forever.css_class('text-danger')
    hr
    .row.justify-content-center.mt-3.mb-3
      = f.submit 'Сохранить', class: "btn btn-primary btn-sm"

app/views/inventories/edit.html.slim
h3.text-center.mt-5 Редактирование ТМЦ

.row.mb-2.pl-3
  = link_to 'Новая ТМЦ', new_inventory_path

= render 'form'

.row.mb-5.pl-3
  = link_to 'Список ТМЦ', inventory_categories_path

app/views/inventories/index.html.slim
h3.text-center.mt-5 Список ТМЦ

.row.mb-2.pl-3
  = link_to 'Новая ТМЦ', new_inventory_path

table.table.table-sm.table-striped.table-light.table-hover.mb-4
  thead.bg-secondary.text-white.small
    tr
      th Наименование
      th Ед. измерения
      th Стоимость, руб
      th Наценка, %
      th Действия

  tbody
    - @inventories.each do |inv|
      tr
        td = inv.name
        th = inv.unit.name
        td = inv.inventory_parameters.last.try :price
        td = inv.inventory_parameters.last.try :margin
        td
          /= link_to 'Показать', pos
          = link_to edit_inventory_path(inv) do
            == material_icon.edit
          = link_to inv, data: { confirm: 'Вы уверены?' }, method: :delete do
            == material_icon.delete_outline.css_class('text-danger ml-2')

app/views/inventories/new.html.slim
h3.text-center.mt-5 Новая ТМЦ

= render 'form'

.row.mb-5.pl-3
  = link_to 'Список ТМЦ', inventory_categories_path

app/views/inventories/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_inventory_path(@inventory)
'|
=< link_to 'Back', inventories_path