config/routes.rb
Rails.application.routes.draw do
  resources :competitors
  resources :calculation_categories
  #resources :customer_categories
  resources :inventory_categories
  #resources :inventories
  resources :units
  resources :accountant_preferences
  #resources :equipment
  resources :positions
  get 'static_pages/home'
  get 'static_pages/help'

  resources :customer_categories do
    collection do
      delete "restore/:id" => "customer_categories#restore", as: :restore
    end
  end
  resources :calculations do
    collection do
      get 'get_unit_and_price', to: "calculations#get_unit_and_price"
      get 'get_customers_prices', to: "calculations#get_customers_prices"
      get 'load_category_percents', to: "calculations#load_category_percents"
      delete "restore/:id" => "calculations#restore", as: :restore
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home' #'calculations#index'

  resources :equipment do
    resources :equipment_parameters do
      member do
        delete 'remove_item', to: 'equipment#remove_item'
      end
    end
  end

  resources :inventories do
    resources :inventory_parameters do
      member do
        delete 'remove_item', to: 'inventories#remove_item'
      end
    end
  end
end

app/models/calculation_category.rb
class CalculationCategory < ApplicationRecord
  has_ancestry orphan_strategy: :rootify
  has_many :calculation_categories_calculations, :dependent => :destroy
  has_many :calculations, through: :calculation_categories_calculations
  has_many :calc_category_percents
  accepts_nested_attributes_for :calc_category_percents
end

app/controllers/calculation_categories_controller.rb
class CalculationCategoriesController < ApplicationController
  before_action :set_calculation_category, only: [:show, :edit, :update, :destroy]

  # GET /calculation_categories
  # GET /calculation_categories.json
  def index
    @calculation_categories = CalculationCategory.all.arrange(order: :name)
  end

  # GET /calculation_categories/1
  # GET /calculation_categories/1.json
  def show
  end

  # GET /calculation_categories/new
  def new
    @calculation_category = CalculationCategory.new
    @calculation_categories = collection_for_parent_select
    build_customer_category_associations
  end

  # GET /calculation_categories/1/edit
  def edit
    @calculation_categories = collection_for_parent_select
    build_customer_category_associations
  end

  # POST /calculation_categories
  # POST /calculation_categories.json
  def create
    @calculation_category = CalculationCategory.new(calculation_category_params)
    @calculation_categories = CalculationCategory.order(name: :asc).map { |u| [ u.name, u.id ] }
    #@calculations = Calculation.where(deleted: false).order(name: :asc).map { |u| [ u.name, u.id ] }
    respond_to do |format|
      if @calculation_category.save
        flash[:success] = 'Категория калькуляций успешно создана.'
        format.html { redirect_to edit_calculation_category_path(@calculation_category) }
        format.json { render :show, status: :created, location: @calculation_category }
      else
        flash[:danger] = 'Ошибка создания категории калькуляций'
        format.html { render :new }
        format.json { render json: @calculation_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calculation_categories/1
  # PATCH/PUT /calculation_categories/1.json
  def update
    @calculation_categories = CalculationCategory.order(name: :asc).map { |u| [ u.name, u.id ] }
    #@calculations = Calculation.where(deleted: false).order(name: :asc).map { |u| [ u.name, u.id ] }
    respond_to do |format|
      if @calculation_category.update(calculation_category_params)
        flash[:success] = 'Категория калькуляций успешно отредактирована.'
        format.html { redirect_to edit_calculation_category_path(@calculation_category) }
        format.json { render :show, status: :ok, location: @calculation_category }
      else
        flash[:danger] = 'Ошибка редактирования категории калькуляций'
        format.html { render :edit }
        format.json { render json: @calculation_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calculation_categories/1
  # DELETE /calculation_categories/1.json
  def destroy
    @calculation_category.destroy
    respond_to do |format|
      flash[:success] = 'Категория калькуляций успешно удалена'
      format.html { redirect_to calculation_categories_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calculation_category
      @calculation_category = CalculationCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calculation_category_params
      params.require(:calculation_category).permit(:name, :parent_id, calculation_ids: [],
        calc_category_percents_attributes: [:id, :calculation_category_id, :customer_category_parameter_id,
        :manager_percent, :profit_percent, :overheads_percent, :tax_percent])
    end

    def collection_for_parent_select
      @categories = ancestry_options(CalculationCategory.unscoped.arrange(order: 'name')) {|i| "#{'-' * i.depth} #{i.name}" }
    end

    def ancestry_options(items)
      result = []
      items.map do |item, sub_items|
        result << [(("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" * item.depth) + item.name).html_safe, item.id]
        result += ancestry_options(sub_items) unless sub_items.blank?
      end
      result
    end

    def build_customer_category_associations
      customers_categories = CustomerCategory.where(deleted: false).all
        customers_categories.each do |cc|
          customer_params = cc.customer_category_parameters.get_actual.map { |r| r.attributes.symbolize_keys }
          customer_params = customer_params.first
          puts "\n" + 'CAT ID= ' + cc.id.inspect + "\n\r"
          @calculation_category.calc_category_percents.build(
            customer_category_id: cc.id,
            customer_category_parameter_id: customer_params[:id],
            manager_percent: customer_params[:manager_percent],
            profit_percent: customer_params[:profit_percent],
            overheads_percent: customer_params[:overheads_percent],
            tax_percent: customer_params[:tax_percent]) unless @calculation_category.calc_category_percents.collect(&:customer_category_parameter_id).include?(customer_params[:id])
      end
    end
end

app/helpers/calculation_categories_helper.rb
module CalculationCategoriesHelper
  def show_calculation_categories_list(categories)

    categories.map do |category, sub_categories|
      (content_tag :div, nil, class: 'accordion-heading' do
        (link_to "#id-#{category.name.gsub(/[\s,]+/, '-').downcase}", class: 'accordion-toggle', data: { toggle: "collapse" } do
          concat content_tag :i, nil, class: 'fa fa-folder'
          concat content_tag :span, "#{category.name}"
          concat tag.span "подкат: #{category.children.count}", class: 'badge badge-success'
          concat tag.span "кальк: #{category.calculations.not_deleted.count}", class: 'badge badge-warning inventories-count'
        end) +
        (tag.div class: 'category-action pull-right' do
          (link_to edit_calculation_category_path(category), target: :_blank do
            (tag.i 'edit', class: "material-icons").html_safe
          end) +
          (link_to category, data: { confirm: 'Вы уверены?' }, method: :delete do
            (tag.i 'delete_forever', class: "material-icons text-danger mx-2").html_safe
          end)
        end)
      end) +

      (content_tag :div, nil, class: 'accordion-body collapse', id: "id-#{category.name.gsub(/[\s,]+/, '-').downcase}" do
        (content_tag :div, nil, class: 'accordion-inner' do
          if category.calculations.not_deleted.present?
            concat (content_tag :table, nil, class: 'table table-striped table-sm table-light table-hover' do
              (content_tag :thead, nil, class: 'category-header' do
                concat (content_tag :tr, class: 'd-flex' do
                  @cust_cat_count = CustomerCategory.not_deleted.count
                  @compet_count = Competitor.not_deleted.count
                  concat content_tag :th, 'Наименование', class: "col-#{11-@cust_cat_count-@compet_count}"
                  CustomerCategory.not_deleted.each do |cc|
                    concat content_tag :th, cc.name, class: 'col-1'
                    end
                  Competitor.not_deleted.each do |cc|
                    concat content_tag :th, cc.name, class: 'col-1'
                  end
                  concat content_tag :th, 'Действия', class: 'col-1'
                end)
              end) +

              (content_tag :tbody do
                category.calculations.not_deleted.order(name: :asc).each do |calc|
                  concat (content_tag :tr, class: 'd-flex' do
                    unit = calc.unit.nil? ? '' : calc.unit.name
                    concat content_tag :td, "#{calc.name+'('+unit+')'}", class: "col-#{11-@cust_cat_count-@compet_count}"
                    #concat content_tag :td, '%.4f' % calc.price, class: 'col-2'
                    if calc.calc_prices.present?
                      calc.calc_prices.each do |cp|
                        concat content_tag :td, '%.2f' % cp.price, class: 'col-1 label-xs'
                      end
                    else
                      @cust_cat_count.times do
                        concat content_tag :td, '-', class: 'col-1 label-xs'
                      end
                    end
                    if calc.calc_competitors.present?
                      calc.calc_competitors.each do |cc|
                        concat content_tag :td, '%.2f' % cc.price, class: 'col-1 label-xs'
                      end
                    else
                      @compet_count.times do
                        concat content_tag :td, '-', class: 'col-1 label-xs'
                      end
                    end
                    concat (content_tag :td, class: 'col-1' do
                      (link_to edit_calculation_path(calc), target: :_blank do
                        content_tag(:i, 'edit', class: "material-icons").html_safe
                      end) +
                      (link_to calc, data: { confirm: 'Вы уверены?' }, method: :delete do
                        content_tag(:i, 'delete_outline', class: "material-icons text-danger ml-2").html_safe
                      end)
                    end)
                  end)
                end
              end)
            end) 
          end
          concat show_calculation_categories_list(sub_categories).html_safe
        end)
      end)
    end.join.html_safe
  end

end

app/views/calculation_categories/_form.html.slim
  = render 'layouts/errors', object: @calculation_category
  
  = form_for @calculation_category do |f|
    .row.mt-5
      .form-group.col-sm-6
        = f.text_field :name, class: 'form-control form-control-sm', required: true
        = f.label :name, 'Наименование', class: 'form-control-placeholder'
      .form-group.col-sm-6
        = f.label :parent_id, 'Родительская категория', class: 'small-label-placeholder'
        = f.select :parent_id, @calculation_categories, { include_blank: '...' }, { class: 'form-control form-control-sm' }
    .row.mt-5
      table.table.table-sm.table-striped.table-light.table-hover.mb-4
        thead.bg-secondary.text-white.small
          tr.d-flex
            th.col-4 Категория потребителей
            th.col-2 Накладные, %
            th.col-2 Сбыт, %
            th.col-2 Прибыль, %
            th.col-2 Налог, %

        tbody
          = f.fields_for :calc_category_percents, @calculation_category.calc_category_percents  do |cp|
            tr.d-flex
              td.col-4
                = cp.object.customer_category_parameter.customer_category.name
                = cp.hidden_field :customer_category_parameter_id
                = cp.hidden_field :customer_category_id, class: 'customer-category-id'
              td.col-2
                = cp.text_field :overheads_percent, class: 'form-control form-control-xs', required: true
              td.col-2
                = cp.text_field :manager_percent, class: 'form-control form-control-xs', required: true
              td.col-2
                = cp.text_field :profit_percent, class: 'form-control form-control-xs', required: true
              td.col-2
                = cp.text_field :tax_percent, class: 'form-control form-control-xs', required: true

    hr
    .row.justify-content-center.mt-3.mb-3
      = f.submit 'Сохранить', class: "btn btn-primary btn-sm"

app/views/calculation_categories/edit.html.slim
h3.text-center.mt-5 Редактирование категории калькуляций

.row.mb-2.pl-3
  = link_to 'Новая категория калькуляций', new_calculation_category_path

= render 'form'

.row.mb-5.pl-3
  = link_to 'Список категорий калькуляций', calculation_categories_path

app/views/calculation_categories/index.html.slim
h3.text-center.mt-5 Список калькуляций

.row.mb-2.pl-3
  .col-xs-9.col-md-9
    = link_to 'Новая категория калькуляций', new_calculation_category_path, target: :_blank
  .col-xs-3.col-md-3.text-right
    = link_to 'Удаленные калькуляции', calculations_path, target: :_blank, class: 'text-danger'
.row.bm-2.pl-3
  .col-xs-9.col-md-10
    = link_to 'Новая калькуляция', new_calculation_path, target: :_blank
  .col-xs-3.col-md-2.d-flex.justify-content-end
    = button_tag '#', class: 'btn btn-outline-primary btn-sm collapse-all' do
      i.fa.fa-compress.fa-rotate-45
    = button_tag '#', class: 'btn btn-outline-primary btn-sm expand-all' do
      i.fa.fa-expand.fa-rotate-45

.row.mt-3.mb-5
  .col-xs-12.col-md-12
    .accordion
      .accordion-group
        = show_calculation_categories_list @calculation_categories

app/views/calculation_categories/new.html.slim
h3.text-center.mt-5 Новая категория калькуляций

= render 'form'

.row.mb-5.pl-3
  = link_to 'Список категорий калькуляций', calculation_categories_path

app/views/calculation_categories/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_calculation_category_path(@calculation_category)
'|
=< link_to 'Back', calculation_categories_path