config/routes.rb
Rails.application.routes.draw do
  resources :competitors
  resources :calculation_categories
  #resources :customer_categories
  resources :inventory_categories
  #resources :inventories
  resources :units
  resources :accountant_preferences
  #resources :equipment
  resources :positions
  get 'static_pages/home'
  get 'static_pages/help'

  resources :customer_categories do
    collection do
      delete "restore/:id" => "customer_categories#restore", as: :restore
    end
  end
  resources :calculations do
    collection do
      get 'get_unit_and_price', to: "calculations#get_unit_and_price"
      get 'get_customers_prices', to: "calculations#get_customers_prices"
      get 'load_category_percents', to: "calculations#load_category_percents"
      delete "restore/:id" => "calculations#restore", as: :restore
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home' #'calculations#index'

  resources :equipment do
    resources :equipment_parameters do
      member do
        delete 'remove_item', to: 'equipment#remove_item'
      end
    end
  end

  resources :inventories do
    resources :inventory_parameters do
      member do
        delete 'remove_item', to: 'inventories#remove_item'
      end
    end
  end
end

app/models/customer_category.rb
class CustomerCategory < ApplicationRecord
  has_many :customer_category_parameters
  accepts_nested_attributes_for :customer_category_parameters

  validates :name, presence: true
  validates :name, uniqueness: true

  scope :not_deleted, -> { where(deleted: false) }
  scope :ordered_by_name, -> { order_by(name: :asc) }
end

app/controllers/customer_categories_controller.rb
class CustomerCategoriesController < ApplicationController
  before_action :set_customer_category, only: [:show, :edit, :update, :destroy, :restore]

  # GET /customer_categories
  # GET /customer_categories.json
  def index
    @customer_categories = CustomerCategory.where(deleted: false).order(name: :asc)
    @removed_customer_categories = CustomerCategory.where(deleted: true)
  end

  # GET /customer_categories/1
  # GET /customer_categories/1.json
  def show
  end

  # GET /customer_categories/new
  def new
    @customer_category = CustomerCategory.new
    @customer_category.customer_category_parameters.build
  end

  # GET /customer_categories/1/edit
  def edit
    @customer_category = CustomerCategory.find(params[:id])
    @customer_category_parameters = CustomerCategoryParameter.get_last(@customer_category.id, 5)
  end

  # POST /customer_categories
  # POST /customer_categories.json
  def create
    @customer_category = CustomerCategory.new(customer_category_params)

    respond_to do |format|
      if @customer_category.save
        CustomerCategoryParameter.set_irrelevant(@customer_category.id)
        @customer_category.customer_category_parameters.set_relevant
        flash[:success] = 'Категория успешно создана.'
        format.html { redirect_to edit_customer_category_path(@customer_category) }
      else
        flash[:danger] = 'Ошибка создания категории.'
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /customer_categories/1
  # PATCH/PUT /customer_categories/1.json
  def update
    respond_to do |format|
      if @customer_category.update(customer_category_params)
        CustomerCategoryParameter.set_irrelevant(@customer_category.id)
        @customer_category.customer_category_parameters.set_relevant
        flash[:success] = 'Категория успешно отредактирована.'
        format.html { redirect_to edit_customer_category_path(@customer_category) }
      else
        flash[:danger] = 'Ошибка редактирования категории.'
        format.html { redirect_to edit_customer_category_path(@customer_category) }
      end
    end
  end

  # DELETE /customer_categories/1
  # DELETE /customer_categories/1.json
  def destroy
    @customer_category.update_column(:deleted, true)
    CalcCategoryPercent.where(customer_category_id: @customer_category.id).destroy_all
    CalcPrice.where(customer_category_id: @customer_category.id).destroy_all

    respond_to do |format|
      #CustomerCategoryParameter.set_irrelevant(@customer_category.id)
      flash[:success] = 'Категория успешно удалено.'
      format.html { redirect_to customer_categories_path }
    end
  end

  def restore
    @customer_category.update_column(:deleted, false)
    respond_to do |format|
      @customer_category.customer_category_parameters.set_relevant
      flash[:success] = 'Категория успешно восстановлена.'
      format.html { redirect_to customer_categories_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_category
      @customer_category = CustomerCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_category_params
      params.require(:customer_category).permit(:name,
        customer_category_parameters_attributes: [:customer_category_id, :user_id, :manager_percent,
          :profit_percent, :overheads_percent, :tax_percent, :actual])
    end
end

app/helpers/customer_categories_helper.rb
module CustomerCategoriesHelper
end

app/views/customer_categories/_form.html.slim
  = render 'layouts/errors', object: @customer_category
  
  = form_for @customer_category do |f|
    .row.mt-5
      .form-group.col-sm-5
        = f.text_field :name, class: 'form-control form-control-sm', required: true
        = f.label :name, 'Наименование', class: 'form-control-placeholder'
      = f.fields_for :customer_category_parameters, @customer_category.customer_category_parameters.build do |cc|
        .form-group.col-sm-2
          = cc.text_field :overheads_percent, class: 'form-control form-control-sm', required: true
          = cc.label :overheads_percent, 'Накладные, %', class: 'form-control-placeholder'
        .form-group.col-sm-2
          = cc.text_field :manager_percent, class: 'form-control form-control-sm', required: true
          = cc.label :manager_percent, 'Сбыт, %', class: 'form-control-placeholder'
        .form-group.col-sm-2
          = cc.text_field :profit_percent, class: 'form-control form-control-sm', required: true
          = cc.label :profit_percent, 'Прибыль, %', class: 'form-control-placeholder'
        .form-group.col-sm-1
          = cc.text_field :tax_percent, class: 'form-control form-control-sm', required: true
          = cc.label :tax_percent, 'Налог, %', class: 'form-control-placeholder'

    - if @customer_category.persisted?
      hr
      .row.col-sm-12.col-xs-12.mb-2.text-muted.small
        .col-sm-2.col-xs-2
          | Накладные, %
        .col-sm-2.col-xs-2
          | Сбыт, %
        .col-sm-2.col-xs-2
          | Прибыль, %
        .col-sm-2.col-xs-2
          | Налог, %
        .col-sm-2.col-xs-2
          | Дата
        .col-sm-2.col-xs-2
          | Создана
      hr.mb-1.mt-1
      - @customer_category_parameters.each do |p|
        .row.col-sm-12.col-xs-12.item-hystory-row
          .col-sm-2.col-xs-2
            = p.overheads_percent
          .col-sm-2.col-xs-2
            = p.manager_percent
          .col-sm-2.col-xs-2
            = p.profit_percent
          .col-sm-2.col-xs-2
            = p.tax_percent
          .col-sm-2.col-xs-2
            = p.created_at.strftime('%d-%m-%Y / %H:%M')
            |&nbsp;
            - if p.actual
              span.badge.bg-success.text-white
                | &nbsp;&nbsp;
            - else
              span.badge.bg-warning.text-white
                | &nbsp;&nbsp;
          .col-sm-2.col-xs-2
            | Имя пользователя
    hr
    .row.justify-content-center.mt-3.mb-3
      = f.submit 'Сохранить', class: "btn btn-primary btn-sm"

app/views/customer_categories/edit.html.slim
h3.text-center.mt-5 Редактирование категории заказчика

.row.mb-2.pl-3
  = link_to 'Новая категория', new_customer_category_path

= render 'form'

.row.mb-5.pl-3
  = link_to 'Список категорий', customer_categories_path

app/views/customer_categories/index.html.slim
h3.text-center.mt-5 Список категорий потребителей

.row.mb-2.pl-3
  = link_to 'Новая категория', new_customer_category_path

table.table.table-sm.table-striped.table-light.table-hover.mb-4
  thead.bg-secondary.text-white.small
    tr
      th Наименование
      th Накладные, %
      th Сбыт, %
      th Прибыль, %
      th Налог, %
      th Действия

  tbody
    - @customer_categories.each do |eq|
      tr
        td = eq.name
        td = eq.customer_category_parameters.last.try :overheads_percent
        td = eq.customer_category_parameters.last.try :manager_percent
        td = eq.customer_category_parameters.last.try :profit_percent
        td = eq.customer_category_parameters.last.try :tax_percent
        td
          /= link_to 'Показать', pos
          = link_to edit_customer_category_path(eq) do
            == material_icon.edit
          = link_to eq, data: { confirm: 'Вы уверены?' }, method: :delete do
            == material_icon.delete_outline.css_class('text-danger ml-2')

h5.text-center.mt-5.text-danger Список удаленных категорий потребителей

- if @removed_customer_categories.present?
  table.table.table-sm.table-striped.table-light.table-hover.mb-4
    thead.bg-secondary.text-white.small
      tr
        th Наименование
        th Накладные, %
        th Сбыт, %
        th Прибыль, %
        th Налог, %
        th Действия

    tbody
      - @removed_customer_categories.each do |eq|
        tr
          td = eq.name
          td = eq.customer_category_parameters.last.try :overheads_percent
          td = eq.customer_category_parameters.last.try :manager_percent
          td = eq.customer_category_parameters.last.try :profit_percent
          td = eq.customer_category_parameters.last.try :tax_percent
          td
            = link_to restore_customer_categories_path(eq), data: { confirm: 'Вы уверены, что хотите восстановить категорию?' }, method: :delete do
              == material_icon.restore_from_trash.css_class('text-success ml-2')
-else
  h6.text-center.mt-2.text-warning Нет удаленных категорий потребителей

app/views/customer_categories/new.html.slim
h3.text-center.mt-5 Новая категория

= render 'form'

.row.mb-5.pl-3
  = link_to 'Список категорий', customer_categories_path

app/views/customer_categories/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_customer_category_path(@customer_category)
'|
=< link_to 'Back', customer_categories_path